Creation of the employee and consultant salary structures json
IntelliSOFT-Consulting/corporate_services pull request #248
Opened 2024-10-16 04:56 UTC by mathewwahome

@brianraila Creation of the employee and consultant salary structures json

2024-10-16 05:50 UTC, brianraila requested changes
@mathewwahome 
Won't the migrations fail when the user mwahome is absent.
Could you create this with the Admin as the owner?

2024-10-16 10:03 UTC, mathewwahome commented
@brianraila Let me update this

2024-10-18 06:23 UTC, mathewwahome commented
> @mathewwahome Won't the migrations fail when the user mwahome is absent. Could you create this with the Admin as the owner? 

@brianraila --Updated

2024-10-18 08:39 UTC, brianraila approved these changes

2024-10-18 08:39 UTC, merged